// 映射表定义

// LaTeX 命令到 Unicode 的映射表
export const LATEX_TO_UNICODE: Record<string, string> = {
    // 希腊字母
    "\\alpha": "α",
    "\\beta": "β",
    "\\gamma": "γ",
    "\\delta": "δ",
    "\\epsilon": "ε",
    "\\varepsilon": "ε",
    "\\zeta": "ζ",
    "\\eta": "η",
    "\\theta": "θ",
    "\\vartheta": "ϑ",
    "\\iota": "ι",
    "\\kappa": "κ",
    "\\lambda": "λ",
    "\\mu": "μ",
    "\\nu": "ν",
    "\\xi": "ξ",
    "\\omicron": "ο",
    "\\pi": "π",
    "\\varpi": "ϖ",
    "\\rho": "ρ",
    "\\varrho": "ϱ",
    "\\sigma": "σ",
    "\\varsigma": "ς",
    "\\tau": "τ",
    "\\upsilon": "υ",
    "\\phi": "φ",
    "\\varphi": "ϕ",
    "\\chi": "χ",
    "\\psi": "ψ",
    "\\omega": "ω",
    "\\Gamma": "Γ",
    "\\Delta": "Δ",
    "\\Theta": "Θ",
    "\\Lambda": "Λ",
    "\\Xi": "Ξ",
    "\\Pi": "Π",
    "\\Sigma": "Σ",
    "\\Upsilon": "Υ",
    "\\Phi": "Φ",
    "\\Psi": "Ψ",
    "\\Omega": "Ω",

    // 运算符
    "\\times": "×",
    "\\div": "÷",
    "\\pm": "±",
    "\\mp": "∓",
    "\\cdot": "·",
    "\\ast": "∗",
    "\\star": "⋆",
    "\\dagger": "†",
    "\\ddagger": "‡",
    "\\amalg": "⨿",
    "\\cap": "∩",
    "\\cup": "∪",
    "\\uplus": "⊎",
    "\\sqcap": "⊓",
    "\\sqcup": "⊔",
    "\\vee": "∨",
    "\\wedge": "∧",
    "\\setminus": "∖",
    "\\wr": "≀",
    "\\circ": "∘",
    "\\bullet": "•",
    "\\oplus": "⊕",
    "\\ominus": "⊖",
    "\\otimes": "⊗",
    "\\oslash": "⊘",
    "\\odot": "⊙",
    "\\bigcirc": "○",
    "\\diamond": "◇",
    "\\bigtriangleup": "△",
    "\\bigtriangledown": "▽",
    "\\triangleleft": "◁",
    "\\triangleright": "▷",
    "\\lhd": "⊲",
    "\\rhd": "⊳",
    "\\unlhd": "⊴",
    "\\unrhd": "⊵",

    // 关系符
    "\\leq": "≤",
    "\\geq": "≥",
    "\\neq": "≠",
    "\\equiv": "≡",
    "\\sim": "∼",
    "\\simeq": "≃",
    "\\approx": "≈",
    "\\cong": "≅",
    "\\bowtie": "⋈",
    "\\propto": "∝",
    "\\in": "∈",
    "\\ni": "∋",
    "\\notin": "∉",
    "\\subset": "⊂",
    "\\supset": "⊃",
    "\\subseteq": "⊆",
    "\\supseteq": "⊇",
    "\\sqsubset": "⊏",
    "\\sqsupset": "⊐",
    "\\sqsubseteq": "⊑",
    "\\sqsupseteq": "⊒",
    "\\prec": "≺",
    "\\succ": "≻",
    "\\preceq": "⪯",
    "\\succeq": "⪰",
    "\\parallel": "∥",
    "\\mid": "∣",
    "\\dashv": "⊣",
    "\\vdash": "⊢",
    "\\models": "⊨",
    "\\perp": "⊥",
    "\\asymp": "≍",
    "\\doteq": "≐",
    "\\ll": "≪",
    "\\gg": "≫",

    // 箭头
    "\\leftarrow": "←",
    "\\rightarrow": "→",
    "\\Leftarrow": "⇐",
    "\\Rightarrow": "⇒",
    "\\leftrightarrow": "↔",
    "\\Leftrightarrow": "⇔",
    "\\mapsto": "↦",
    "\\hookleftarrow": "↩",
    "\\hookrightarrow": "↪",
    "\\leftharpoonup": "↼",
    "\\leftharpoondown": "↽",
    "\\rightharpoonup": "⇀",
    "\\rightharpoondown": "⇁",
    "\\rightleftharpoons": "⇌",
    "\\longleftarrow": "⟵",
    "\\longrightarrow": "⟶",
    "\\Longleftarrow": "⟸",
    "\\Longrightarrow": "⟹",
    "\\longleftrightarrow": "⟷",
    "\\Longleftrightarrow": "⟺",
    "\\longmapsto": "⟼",
    "\\uparrow": "↑",
    "\\downarrow": "↓",
    "\\Uparrow": "⇑",
    "\\Downarrow": "⇓",
    "\\updownarrow": "↕",
    "\\Updownarrow": "⇕",
    "\\nearrow": "↗",
    "\\searrow": "↘",
    "\\swarrow": "↙",
    "\\nwarrow": "↖",

    // 逻辑符号
    "\\forall": "∀",
    "\\exists": "∃",
    "\\nexists": "∄",
    "\\neg": "¬",
    "\\top": "⊤",
    "\\bot": "⊥",
    "\\land": "∧",
    "\\lor": "∨",
    "\\to": "→",

    // 集合符号
    "\\emptyset": "∅",
    "\\varnothing": "∅",
    "\\aleph": "ℵ",
    "\\imath": "ı",
    "\\jmath": "ȷ",
    "\\ell": "ℓ",
    "\\wp": "℘",
    "\\Re": "ℜ",
    "\\Im": "ℑ",
    "\\partial": "∂",
    "\\infty": "∞",
    "\\nabla": "∇",
    "\\triangle": "△",
    "\\Box": "□",
    "\\Diamond": "◇",
    "\\hbar": "ℏ",
    "\\angle": "∠",
    "\\clubsuit": "♣",
    "\\diamondsuit": "♢",
    "\\heartsuit": "♡",
    "\\spadesuit": "♠",

    // 积分和求和
    "\\int": "∫",
    "\\iint": "∬",
    "\\iiint": "∭",
    "\\oint": "∮",
    "\\oiint": "∯",
    "\\oiiint": "∰",
    "\\sum": "∑",
    "\\prod": "∏",
    "\\coprod": "∐",
    "\\bigcup": "⋃",
    "\\bigcap": "⋂",
    "\\bigvee": "⋁",
    "\\bigwedge": "⋀",
    "\\biguplus": "⨄",
    "\\bigsqcup": "⨆",
    "\\bigodot": "⨀",
    "\\bigotimes": "⨂",
    "\\bigoplus": "⨁",

    // 括号
    "\\langle": "⟨",
    "\\rangle": "⟩",
    "\\lfloor": "⌊",
    "\\rfloor": "⌋",
    "\\lceil": "⌈",
    "\\rceil": "⌉",
    "\\{": "{",
    "\\}": "}",
    "\\|": "‖",

    // 其他
    "\\ldots": "…",
    "\\cdots": "⋯",
    "\\vdots": "⋮",
    "\\ddots": "⋱",
    "\\surd": "√",
    "\\prime": "′",
    "\\sharp": "♯",
    "\\flat": "♭",
    "\\natural": "♮",
    "\\mho": "℧",
    "\\Join": "⋈",
    "\\smile": "⌣",
    "\\frown": "⌢",

    // 函数名
    "\\sin": "sin",
    "\\cos": "cos",
    "\\tan": "tan",
    "\\cot": "cot",
    "\\sec": "sec",
    "\\csc": "csc",
    "\\arcsin": "arcsin",
    "\\arccos": "arccos",
    "\\arctan": "arctan",
    "\\sinh": "sinh",
    "\\cosh": "cosh",
    "\\tanh": "tanh",
    "\\log": "log",
    "\\ln": "ln",
    "\\exp": "exp",
    "\\lim": "lim",
    "\\max": "max",
    "\\min": "min",
    "\\sup": "sup",
    "\\inf": "inf",
    "\\det": "det",
    "\\gcd": "gcd",
    "\\Pr": "Pr",
};

// 数字上标映射（Unicode 上标字符）
export const SUPERSCRIPT_MAP: Record<string, string> = {
    "0": "⁰",
    "1": "¹",
    "2": "²",
    "3": "³",
    "4": "⁴",
    "5": "⁵",
    "6": "⁶",
    "7": "⁷",
    "8": "⁸",
    "9": "⁹",
    "+": "⁺",
    "-": "⁻",
    "=": "⁼",
    "(": "⁽",
    ")": "⁾",
    a: "ᵃ",
    b: "ᵇ",
    c: "ᶜ",
    d: "ᵈ",
    e: "ᵉ",
    f: "ᶠ",
    g: "ᵍ",
    h: "ʰ",
    i: "ⁱ",
    j: "ʲ",
    k: "ᵏ",
    l: "ˡ",
    m: "ᵐ",
    n: "ⁿ",
    o: "ᵒ",
    p: "ᵖ",
    r: "ʳ",
    s: "ˢ",
    t: "ᵗ",
    u: "ᵘ",
    v: "ᵛ",
    w: "ʷ",
    x: "ˣ",
    y: "ʸ",
    z: "ᶻ",
    A: "ᴬ",
    B: "ᴮ",
    D: "ᴰ",
    E: "ᴱ",
    G: "ᴳ",
    H: "ᴴ",
    I: "ᴵ",
    J: "ᴶ",
    K: "ᴷ",
    L: "ᴸ",
    M: "ᴹ",
    N: "ᴺ",
    O: "ᴼ",
    P: "ᴾ",
    R: "ᴿ",
    T: "ᵀ",
    U: "ᵁ",
    V: "ⱽ",
    W: "ᵂ",
    α: "ᵅ",
    β: "ᵝ",
    γ: "ᵞ",
    δ: "ᵟ",
    ε: "ᵋ",
    θ: "ᶿ",
    ι: "ᶥ",
    υ: "ᶷ",
    φ: "ᶲ",
    χ: "ᵡ",
};

// 数字下标映射（Unicode 下标字符）
export const SUBSCRIPT_MAP: Record<string, string> = {
    "0": "₀",
    "1": "₁",
    "2": "₂",
    "3": "₃",
    "4": "₄",
    "5": "₅",
    "6": "₆",
    "7": "₇",
    "8": "₈",
    "9": "₉",
    "+": "₊",
    "-": "₋",
    "=": "₌",
    "(": "₍",
    ")": "₎",
    a: "ₐ",
    e: "ₑ",
    h: "ₕ",
    i: "ᵢ",
    j: "ⱼ",
    k: "ₖ",
    l: "ₗ",
    m: "ₘ",
    n: "ₙ",
    o: "ₒ",
    p: "ₚ",
    r: "ᵣ",
    s: "ₛ",
    t: "ₜ",
    u: "ᵤ",
    v: "ᵥ",
    x: "ₓ",
    y: "ᵧ",
    β: "ᵦ",
    γ: "ᵧ",
    ρ: "ᵨ",
    φ: "ᵩ",
    χ: "ᵪ",
};

// 重音符号组合（Unicode 组合字符）
export const ACCENT_COMBINING: Record<string, string> = {
    "\\hat": "\u0302", // x̂
    "\\tilde": "\u0303", // x̃
    "\\bar": "\u0304", // x̄
    "\\overline": "\u0305", // x̅
    "\\vec": "\u20D7", // x⃗
    "\\dot": "\u0307", // ẋ
    "\\ddot": "\u0308", // ẍ
    "\\acute": "\u0301", // x́
    "\\grave": "\u0300", // x̀
    "\\breve": "\u0306", // x̆
    "\\check": "\u030C", // x̌
    "\\mathring": "\u030A", // x̊
};

// 可扩展箭头映射
export const XARROW_MAP: Record<string, string> = {
    "\\xrightarrow": "→",
    "\\xleftarrow": "←",
    "\\xRightarrow": "⇒",
    "\\xLeftarrow": "⇐",
    "\\xleftrightarrow": "↔",
    "\\xLeftrightarrow": "⇔",
    "\\xhookleftarrow": "↩",
    "\\xhookrightarrow": "↪",
    "\\xtwoheadrightarrow": "↠",
    "\\xtwoheadleftarrow": "↞",
    "\\xmapsto": "↦",
    "\\xlongequal": "═",
};
